name: Create and Populate Repo

on:
  workflow_dispatch:
    inputs:
      repo-name:
        description: 'Name of the new repository (base name)'
        required: true
        default: 'new-repo'
      folder-path:
        description: 'Path to the folder to copy over'
        required: true
        default: './'

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Create New Repository
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          gh repo create "$REPO_NAME" --private --clone
          echo "Repository $REPO_NAME created."

      - name: Push Files
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          FOLDER_PATH="${{ github.event.inputs.folder-path }}"
          cd "$REPO_NAME"
          cp -r ../"$FOLDER_PATH"/* .
          git add .
          git commit -m "Initial commit"
          git push -u origin main
