name: Create and Populate Repo

on:
  workflow_dispatch:
    inputs:
      candidate:
        description: 'Candidate''s username to invite'
        required: true
        default: 'edwinyeehl'
      folder-path:
        description: 'Path to the folder to copy over (v1/v2/v3)'
        required: true
        default: 'v3'

permissions:
  contents: write

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Generate Repository Name
        id: generate-name
        env:
          CANDIDATE: ${{ github.event.inputs.candidate }}
        run: |
          GENERATED_NAME="test-$CANDIDATE-$(date +%s)"
          echo "User provided repo name: $GENERATED_NAME"
          echo "::set-output name=repo-name::$GENERATED_NAME"

      - name: Create New Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPO_NAME: ${{ steps.generate-name.outputs.repo-name }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d "{\"name\":\"$REPO_NAME\",\"private\":true}" \
          https://api.github.com/user/repos


      - name: Configure Git Identity
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          git config --global user.name "$REPO_OWNER"
          git config --global user.email "$REPO_OWNER@users.noreply.github.com"

      - name: Push Files
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          REPO_NAME: ${{ steps.generate-name.outputs.repo-name }}
          FOLDER_PATH: ${{ github.event.inputs.folder-path }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          echo "Path to copy over: $FOLDER_PATH."
          git clone https://x-access-token:$GITHUB_TOKEN@github.com/$REPO_OWNER/$REPO_NAME.git
          cd "$REPO_NAME"
          if [ -d "../$FOLDER_PATH" ] && [ "$(ls -A ../$FOLDER_PATH)" ]; then
            mkdir -p ./"$FOLDER_PATH"
            cp -r ../"$FOLDER_PATH"/* ./"$FOLDER_PATH"/
          else
            echo "Folder $FOLDER_PATH is empty or does not exist!"
            exit 1
          fi
          cp ../README.md . || echo "README.md not found, skipping"
          mkdir -p .github/workflows
          cp ../.github/workflows/main.yml .github/workflows/main.yml || echo "Workflow main.yml not found, skipping"
          cp ../.github/workflows/no-changes.txt .github/workflows/no-changes.txt || echo "Workflow no-changes.txt not found, skipping"
          git add .
          git commit -m "Initial commit"
          git branch -M main
          git push origin main

      - name: Invite collaborator
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          CANDIDATE: ${{ github.event.inputs.candidate }}
          REPO_NAME: ${{ steps.generate-name.outputs.repo-name }}
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          echo "Candidate to invite: $CANDIDATE."
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/collaborators/$CANDIDATE