name: Create and Populate Repo

on:
  workflow_dispatch:
    inputs:
      candidate:
        description: 'Candidate''s username to invite'
        required: true
      folder-path:
        description: 'Path to the folder to copy over'
        required: true
        default: 'v1'

permissions:
  contents: write

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
      
      - name: Generate Repository Name
        id: generate-name
        run: |
          GENERATED_NAME="test-${{ github.event.inputs.candidate }}"
          echo "User provided repo name: $GENERATED_NAME"
          echo "::set-output name=repo-name::$GENERATED_NAME"

      - name: Create New Repository
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          gh repo create "$REPO_NAME" --private --clone --disable-issues --disable-wiki
          echo "Repository $REPO_NAME created."
      
      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Set up Authentication
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/"$REPO_NAME".git

      - name: Push Files
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          FOLDER_PATH="${{ github.event.inputs.folder-path }}"
          echo "Path to copy over: $FOLDER_PATH."
          cd "$REPO_NAME"
          ls -la ..
          echo "Checking if v3 exists:"
          ls -la ../v3
          if [ -d "../$FOLDER_PATH" ] && [ "$(ls -A ../$FOLDER_PATH)" ]; then
            mkdir -p ./"$FOLDER_PATH"
            cp -r ../"$FOLDER_PATH"/* ./"$FOLDER_PATH"/
          else
            echo "Folder $FOLDER_PATH is empty or does not exist!"
            exit 1
          fi
          cp ../README.md . || echo "README.md not found, skipping"
          mkdir -p .github/workflows
          cp ../.github/workflows/main.yml .github/workflows/main.yml || echo "Workflow main.yml not found, skipping"
          cp ../.github/workflows/no-changes.txt .github/workflows/no-changes.txt || echo "Workflow no-changes.txt not found, skipping"
          git add .
          git commit -m "Initial commit"
          git branch -M main
          git push -u origin main

      - name: Invite collaborator
        run: |
          CANDIDATE="${{ github.event.inputs.candidate }}"
          echo "Candidate to invite: $CANDIDATE."
