name: Create and Populate Repo

on:
  workflow_dispatch:
    inputs:
      folder-path:
        description: 'Path to the folder to copy over'
        required: true
        default: './'
      candidate:
        description: 'Candidate''s username to invite'
        required: true

jobs:
  create-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repository
        uses: actions/checkout@v4

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"
      
      - name: Generate Repository Name
        id: generate-name
        run: |
          GENERATED_NAME="test-${{ github.event.inputs.candidate }}"
          echo "User provided repo name: $GENERATED_NAME"
          echo "::set-output name=repo-name::$GENERATED_NAME"
          

      - name: Create New Repository
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          echo "Repository $REPO_NAME created."

      - name: Push Files
        run: |
          REPO_NAME="${{ steps.generate-name.outputs.repo-name }}"
          FOLDER_PATH="${{ github.event.inputs.folder-path }}"
          echo "Path to copy over: $FOLDER_PATH."
          echo "Current Directory: $PWD"
          ls -la $PWD
          cd "$REPO_NAME"
          echo "Current Directory: $PWD"
          ls -la $PWD
          echo "Workflow Directory: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE

      - name: Invite collaborator
        run: |
          CANDIDATE="${{ github.event.inputs.candidate }}"
          echo "Candidate to invite: $CANDIDATE."
